id: IE9916CA7
legacy_id: P001826
ocr_import_info:
  bdrc_scan_id: W703
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T18:08:53'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:11:39.204641+00:00'
last_modified: 2022-09-04 11:11:57.583483
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W703
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW703
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དུས་འཁོར་སྤྱི་དོན་བསྟན་པའི་རྒྱ་མཚོ།
  author: སྟག་ཚང་ལོ་ཙཱ་བ་ཤེས་རབ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.6710758459848228
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I1KG9559:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9559
      total_pages: 562
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9559.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6710758459848228
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
