id: IE9916CA7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T18:12:41+00:00'
last_modified: '2022-06-07T15:17:23.903864+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W703
  title: དུས་འཁོར་སྤྱི་དོན་བསྟན་པའི་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '2397':
      image_group_id: I1KG9559
      title: ''
      total_pages: 562
      order: 1
      base_file: 2397.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
