id: P001826
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W703
  title: དུས་འཁོར་སྤྱི་དོན་བསྟན་པའི་རྒྱ་མཚོ།
  author: ''
  volumes:
    1c065ef3f5a540ef893b23e487dcdeb8:
      image_group_id: I1KG9559
      title: ''
      volume_number: 1
      total_pages: 562
      base_file: v001.txt
